# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aziret
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: product-service-be
# "service" is the name of this project. This will also be added to your AWS resource names.
service: product-service-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: dev

functions:
  getProductsList:
    handler: handlers/products.getProducts
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler: handlers/getProduct.getProduct
    events:
      - http:
          path: products/{productId}
          method: get
          request:
            parameters:
              paths:
                productId: true
